# This file was generated by GoReleaser. DO NOT EDIT.
cask "md" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "caf44dea5b1f0453967499fbd81a1da86a35652e832649aabe63709fe2ac58a6"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "39f5d37cb725d221f1a49be631c05ae0a40e43ce83ac3331cc9d4ebd4e390b01"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7b50c2ff3ed69aba1e782baaab8046ae8caf7081bda236b4a6a993a8427d1041"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "372d5d410d619724690b205bddb67a9ef7f011e2a7338af280e7ecd0195b00f5"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_linux_arm64.tar.gz"
    end
  end

  name "md"
  desc "A terminal Mastodon client with a Claude Code-style TUI and live timelines"
  homepage "https://github.com/prvrtl/mastodon-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md"]
    end
  end

  # No zap stanza required

end
