# This file was generated by GoReleaser. DO NOT EDIT.
cask "md" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "ef043ddb5ec436e13fc7a5f12db63242335d4a68f185e30f74a14a22e817a91f"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "926fcfb5beffd86aedb04ec95894f81340c274c358c4f005c2a069a938878aa2"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69d3bcc28f0ffb18468bd8040f5225e3e69a94936bd15165de6ad7a9e8a52da1"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bb43146c1b7fa2d217538c300704379d1931d227d75c8a6d2c8c29190fc77d8"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_linux_arm64.tar.gz"
    end
  end

  name "md"
  desc "A terminal Mastodon client with a Claude Code-style TUI and live timelines"
  homepage "https://github.com/prvrtl/mastodon-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md"]
    end
  end

  # No zap stanza required

end
