# This file was generated by GoReleaser. DO NOT EDIT.
cask "md" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "66f677118b40606875e6fb13177800cbf93b1f0c7cc6624df1ad07098e5fe3da"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ef61ddcdcc0ccaa1f9740ce49ec8583cae7d86d834d6d654dd53eeadb305932"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f8371c1dc4fa3131dcef4895574fed5374b842e04e81cdb447a09b564ffefcd"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6081914551f9d38ce29c207e1f1a7c84bff051accb5a9dc2f111d4efce89d11c"
      url "https://github.com/prvrtl/mastodon-cli/releases/download/v#{version}/md_#{version}_linux_arm64.tar.gz"
    end
  end

  name "md"
  desc "A terminal Mastodon client with a modern TUI and live timelines"
  homepage "https://github.com/prvrtl/mastodon-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "md"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/md"]
    end
  end

  # No zap stanza required

end
